let quotes = [
`A Safety Data Sheet is a document that provides information on the properties of hazardous chemicals and how they affect health and safety in the workplace.`,
`Anytime a lift is completing a move pedestrians must maintain 20-feet of distance from the lift.`,
`Anytime an associate is within 20-feet the driver should wait to complete the move until the associate is at least 20-feet away.`,
`When opening a trailer always check that it is chalked and that there the TCR  on the door matches the trailer in the door.`,
`Always participate in stretching and stretch to your ability.`,
`Always complete your safety training.`,
`Always wear proper PPE.`,
`Only licensed associates can operate power equipment. The license must be available and on the operator’s person at all times when operating power equipment.`,
`Stop at all fire wall doors regardless of the direction of travel. Stop before going through the fire wall doors and before passing in front of the fire wall doors.`,
`Stay alert while operating any vehicle. Do not drive over bands, wood, string, tape, or any object which could re-direct steering or damage wheels.`,
`When lifting, use the weight and momentum of the case to deliver it to the end point. However, never throw freight. With elbows slightly bent, pick up the case.`,
`When lifting, always lead with your feet. After lifting a case, move your feet to eliminate twisting at the waist. Always move your feet to stay in front of the work being done.`,
`When parking a forklift, tilt forks down and on the floor, and never put the forks under another lift.`,
`All associates operating powered equipment must be licensed through the Walmart Logistics power equipment training process.`,
`Everyone is responsible for their own and all other associates safety.`,
`When using a box knife, apply a consistent, firm (but not excessive) pressure while performing the cut.`,
`Obtain management authorization and notify Asset Protection before driving up or down the outside ramp.`,
`Lift large cases by tilting them on a 45-degree angle and lift evenly with your shoulders.`,
`When picking up small items with one hand, keep your wrist straight and in a neutral position. The wrist is designed to flex up and down, like shaking hands. The thumb should be pointed up as much as possible to eliminate stress on the wrist.`,
`When lifting, keep your shoulders square and avoid twisting your shoulders from side-to-side. To securely and evenly lift a load, use the handholds in case (if available) or reach under the case.`,
`Slide the case as close to you as possible prior to lifting the load.`,
`Never stand or walk under the forks of a forklift, regardless of whether it is loaded or unloaded.`,
`For your safety, never sit, climb or stand on stacks of merchandise, pallets, cartons, boxes, or racks. Never walk, ride, stand, or climb on or over machines or equipment. Never use carts, pallets, hand jacks and forks on lifts, cartons or boxes as a stepping stool.`,
`Before moving a piece of equipment, always look in the direction of travel and side-to-side to ensure your path is clear. This is true even when moving short distances. Never drive into a main aisle with the forks or basket first.`,
`After using a box knife, always retract the razorblade into the box knife handle, and if the blade has become dull or is broken, replace it.`,
`Be careful not to strike overhead objects such as cross aisles, conveyors, and fans.`,
`You should never leave power equipment unattended. If you are 25 feet or more away, you must fully lower the load engaging means and shut off the power. `,
`Unclean work areas are a common safety hazard that can lead to injuries. Make sure you clean as you go!`,
`When bending, bend at the knees, not the waist. Use the legs to lift and keep the back as straight as possible.`,
`When loading a pallet, stack cartons straight and stable for a secure load.`,
`Do not double pallet freight in racks. Also, never use bad pallets.`,
`Pallets should always be stacked flat and neatly on the floor.`,
`Always park motorized equipment in designated parking areas and walk to/from the break rooms at break, lunch, and dinner. At the end of the shift, park your lift in the designated lift parking area for your area (for example, Shipping or Receiving). Never park equipment on a dock plate.`,
`All areas must be kept clean so that the area does not create a safety hazard to yourself or others.`,
`When bending, bend at the knees, not the waist. Use the legs to lift and keep the back as straight as possible.`,
`Prior to lifting a case, strategize about where you are going to place it. Knowing where you are going to place a case prior to lifting will save you from lifting the case longer than necessary.`,
`All associates should cooperate with the Safety Team and actively support any Safety Team activities by contributing ideas and suggestions for improving the conditions or procedures to a manager.`,
`When operating power equipment, approach all individuals and objects with caution and give yourself room to brake safely (braking speed differs from machine to machine). Remember to drive defensively, yield to pedestrians, and always come to a complete stop before getting off equipment.`,
`No modifications on equipment are allowed (for example: no writing or marking on equipment).`,
`When operating power equipment, do not tailgate. Always drive in a single line with a minimum of three (3) lengths between vehicles – unless you are passing in opposite directions`,
`When lifting, always face your work. Square up to what is being lifted to eliminate twist and stress. Also, square up to the delivery point prior to setting the case down.`,
`When placing a case on a pallet (or conveyor), do not over-extend yourself. Place the case on the edge of the pallet and slide it into position.`,
`Pedestrians must maintain a safe distance around operating forklifts and/or power equipment, especially when the load is moved up or down or there is an overhead load.`,
`If there is a fire, power failure, or an emergency in the facility, stop your PE immediately and lower your load (if possible).`,
`Safety Data Sheets (SDS) of hazardous chemicals in your facility are available to you by navigating to OneWire > Safety Data Sheets`,
`When parking, or when more than 25 feet away from power equipment in use, leave easy access to aisles, firefighting equipment, and stairways. Also remember to lower and tilt forks to the floor and turn off the vehicle (switch in the off position).`,
`Always check the trailer floor before entering with power equipment. If the floor looks unsafe, contact a manager to check the floors before entering. Drive around liquid spills. Report or clean up liquid spills immediately.`,
`If you experience mechanical malfunction during the operation of a PE, park the power equipment immediately and notify Maintenance or a manager.`,
`Don't talk to associates on power equipment`,
`Stay hydrated`,
]
function myFunction(){
		let randomNumber = Math.floor(Math.random() * (quotes.length));
		alert(quotes[randomNumber]);
	}
		